name: Deploy React App with Docker

on:
  push:
    branches:
      - master   # Run this workflow only when code is pushed to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      # Step 5: Deploy on server (via SSH)
      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Stop and remove old container if exists
            docker stop react-app || true
            docker rm react-app || true
            
            # Remove old image if exists
            docker rmi ${{ secrets.DOCKER_USERNAME }}/react-app:latest || true
            
            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest

            # Run new container
            docker run -d -p 3000:3000 --name react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest
